# Metadata about this component, to be used in the CMS
spec:
  structures: []
  label: Certificates Card
  description: Certificates card used for displaying achievements
  icon: school
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  certificate-item:
    name: ""
    issuer: ""
    when: ""
    description: ""
    link: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  certificate-item:
    name: Web Development Fundamentals
    issuer: Codecademy
    date: "2023-05-15"
    description: Comprehensive course covering HTML, CSS, and JavaScript
    link: https://www.codecademy.com/learn/paths/web-development

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}