# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Education
  description: Education Section with heading, a description and a list of educational experiences
  icon: school
  tags:
    - Content

# Defines the structure of this component, as well as the default values
blueprint:
  title: ""
  description_html: ""
  show_educations: true

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  title: Education & Qualifications
  description_html: ""

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
